### ISSUE TITLE
docker build fails 

### ISSUE THREAD

**Issue by aforsythe** [cboulanger/humhub-docker#6]
Cloned and attempted to build but docker build fails due to inability to find server during apt-get

$ docker build .
Sending build context to Docker daemon 223.7 kB
Step 1 : FROM cboulanger/turnkeylinux-lamp:v14.0
 ---> 5952fc26ddf6
Step 2 : MAINTAINER Christian Boulanger "info@bibliograph.org"
 ---> Using cache
 ---> 941ac64cec47
Step 3 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 556a2aa92eee
Step 4 : RUN apt-get install -y -q php5-gd php5-curl php5-sqlite php5-ldap php5-intl php-apc wget cron
 ---> Running in b02dd5e050ac
Reading package lists...
Building dependency tree...
Reading state information...
cron is already the newest version.
wget is already the newest version.
The following extra packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0
  libjpeg62-turbo libtiff5 libvpx1 libx11-6 libx11-data libxau6 libxcb1
  libxdmcp6 libxpm4 php5-apcu
Suggested packages:
  libgd-tools
The following packages will be REMOVED:
  php5-xcache
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0
  libjpeg62-turbo libtiff5 libvpx1 libx11-6 libx11-data libxau6 libxcb1
  libxdmcp6 libxpm4 php-apc php5-apcu php5-curl php5-gd php5-intl php5-ldap
  php5-sqlite
0 upgraded, 21 newly installed, 1 to remove and 0 not upgraded.
Need to get 4051 kB of archives.
After this operation, 11.6 MB of additional disk space will be used.
Err http://security.debian.org/ jessie/updates/main php5-curl amd64 5.6.14+dfsg-0+deb8u1
  404  Not Found [IP: 149.20.20.19 80]
Err http://security.debian.org/ jessie/updates/main php5-gd amd64 5.6.14+dfsg-0+deb8u1
  404  Not Found [IP: 149.20.20.19 80]
Err http://security.debian.org/ jessie/updates/main php5-intl amd64 5.6.14+dfsg-0+deb8u1
  404  Not Found [IP: 149.20.20.19 80]
Err http://security.debian.org/ jessie/updates/main php5-ldap amd64 5.6.14+dfsg-0+deb8u1
  404  Not Found [IP: 149.20.20.19 80]
Err http://security.debian.org/ jessie/updates/main php5-sqlite amd64 5.6.14+dfsg-0+deb8u1
  404  Not Found [IP: 149.20.20.19 80]
Get:1 http://http.debian.net/debian/ jessie/main fonts-dejavu-core all 2.34-1 [1047 kB]
Get:2 http://http.debian.net/debian/ jessie/main fontconfig-config all 2.11.0-6.3 [273 kB]
Get:3 http://http.debian.net/debian/ jessie/main libjpeg62-turbo amd64 1:1.3.1-12 [116 kB]
Get:4 http://http.debian.net/debian/ jessie/main libjbig0 amd64 2.1-3.1 [30.7 kB]
Get:5 http://http.debian.net/debian/ jessie/main libxcb1 amd64 1.10-3+b1 [44.4 kB]
Get:6 http://http.debian.net/debian/ jessie/main libx11-data all 2:1.6.2-3 [126 kB]
Get:7 http://http.debian.net/debian/ jessie/main libfontconfig1 amd64 2.11.0-6.3 [329 kB]
Get:8 http://http.debian.net/debian/ jessie/main libxpm4 amd64 1:3.5.11-1+b1 [48.1 kB]
Err http://http.debian.net/debian/ jessie/main libgd3 amd64 2.1.0-5
  404  Not Found [IP: 198.145.20.143 80]
Get:9 http://http.debian.net/debian/ jessie/main php5-apcu amd64 4.0.7-1 [80.7 kB]
Err http://http.debian.net/debian/ jessie/main libtiff5 amd64 4.0.3-12.3
  404  Not Found [IP: 128.177.205.145 80]
Get:10 http://http.debian.net/debian/ jessie/main libvpx1 amd64 1.3.0-3 [599 kB]
Get:11 http://http.debian.net/debian/ jessie/main php-apc all 4.0.7-1 [4642 B]
Get:12 http://http.debian.net/debian/ jessie/main libxau6 amd64 1:1.0.8-1 [20.7 kB]
Get:13 http://http.debian.net/debian/ jessie/main libxdmcp6 amd64 1:1.1.1-1+b1 [24.9 kB]
Get:14 http://http.debian.net/debian/ jessie/main libx11-6 amd64 2:1.6.2-3 [729 kB]
Fetched 3472 kB in 2s (1199 kB/s)
E: Failed to fetch http://http.debian.net/debian/pool/main/t/tiff/libtiff5_4.0.3-12.3_amd64.deb  404  Not Found [IP: 128.177.205.145 80]

E: Failed to fetch http://http.debian.net/debian/pool/main/libg/libgd2/libgd3_2.1.0-5_amd64.deb  404  Not Found [IP: 198.145.20.143 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/p/php5/php5-curl_5.6.14+dfsg-0+deb8u1_amd64.deb  404  Not Found [IP: 149.20.20.19 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/p/php5/php5-gd_5.6.14+dfsg-0+deb8u1_amd64.deb  404  Not Found [IP: 149.20.20.19 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/p/php5/php5-intl_5.6.14+dfsg-0+deb8u1_amd64.deb  404  Not Found [IP: 149.20.20.19 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/p/php5/php5-ldap_5.6.14+dfsg-0+deb8u1_amd64.deb  404  Not Found [IP: 149.20.20.19 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/p/php5/php5-sqlite_5.6.14+dfsg-0+deb8u1_amd64.deb  404  Not Found [IP: 149.20.20.19 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -y -q php5-gd php5-curl php5-sqlite php5-ldap php5-intl php-apc wget cron' returned a non-zero code: 100

**Comment by aforsythe** [comment]
looks like it needs 

RUN apt-get update

Experiencing other issues too

**Comment by cboulanger** [comment]
Thanks for reporting. I will add this!

**Comment by cboulanger** [comment]
Fixed with 64a30a95f412947c154bac6b6aa36ad7116c1cb5.
