### ISSUE TITLE
Errors in pre-conf.sh

### ISSUE THREAD

**Issue by aforsythe** [cboulanger/humhub-docker#7]
Step 23 : RUN (/bin/bash -c /pre-conf.sh)
 ---> Running in 598d9c4727f2
160722 21:50:11 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
160722 21:50:11 mysqld_safe Logging to '/var/log/mysql/error.log'.
160722 21:50:11 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
Database initialized ...
160722 21:50:17 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
no crontab for www-data
Installed cron jobs ...

**Comment by cboulanger** [comment]
Looks like diagnostic messages to me, no fatal errors here...

**Comment by cboulanger** [comment]
Erros do not prevent successful build & run. It would be great to get rid of them, and I am grateful for suggestions. Won't fix them myself for the time being.
