### ISSUE TITLE
Running cronjob of humhub

### ISSUE THREAD

**Issue by SaiNageswarS** [cboulanger/humhub-docker#8]
Hi..

I'm not able to run cronjobs of humhub to refresh ldap users with this docker image.. Any pointer would be great..
Thanks

**Comment by cboulanger** [comment]
Can you describe your problem in more detail? Are you referring to the standard cronjobs? What happens if you run then manually - you should get some diagnostic output. Since I don't work with LDAP, I won't be able to help you with anything that concerns LDAP integration itself.
